[package]
name = "erl_tokenize"
version = "0.3.9"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
description = "Erlang source code tokenizer"
homepage = "https://github.com/sile/erl_tokenize"
repository = "https://github.com/sile/erl_tokenize"
readme = "README.md"
keywords = ["erlang", "tokenizer", "lexer"]
categories = ["parser-implementations"]
license = "MIT"
edition = "2018"

[badges]
coveralls = {repository = "sile/erl_tokenize"}

[dependencies]
num = "0.4"
thiserror = "1"

[dev-dependencies]
anyhow = "1"
structopt = "0.3"